language: node_js
sudo: required
node_js:
  - "6"
  - "node"
script: 'npm run coverage'
before_script: 
  - sudo rm -f /var/lib/dpkg/lock    
  - sudo rm -f /var/cache/apt/archives/lock
  - sudo dpkg --configure -a
after_script: 'npm run coveralls'
